version: '3.7'
services:
    mongo:
        image: docker.uclv.cu/mongo:latest
        restart: always
        ports:
            - 27017:27017
        volumes:
            - "./tools/data/mongodata:/data/db"